import React,{useState} from 'react';
import experience from '../data/experienceData.json';
import schools from '../data/educationData.json';
import Icon,{GlassIcon} from '../ui/Icon';
import {PageHeader,asset} from '../ui/shared';

function startDate(date:string){const year=Number(date.match(/\b20\d{2}\b/)?.[0]||0);const months=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'];return year*12+Math.max(0,months.indexOf(date.slice(0,3).toLowerCase()));}
const ordered=experience.map((e,index)=>({...e,index,year:e.date.match(/\b20\d{2}\b/)?.[0]||'Earlier'})).sort((a,b)=>startDate(b.date)-startDate(a.date));
function RoadCurve(){return <svg className="road-curve" viewBox="0 0 140 280" preserveAspectRatio="none" aria-hidden="true"><path className="road-shadow" d="M70 0C-5 55-5 85 70 140S145 225 70 280"/><path className="road-body" d="M70 0C-5 55-5 85 70 140S145 225 70 280"/><path className="road-center" d="M70 0C-5 55-5 85 70 140S145 225 70 280"/></svg>;}
export default function Journey({education}:{education:boolean}){
  const [year,setYear]=useState('All years');
  const years=['All years',...Array.from(new Set(ordered.map(e=>e.year)))];
  const entries=ordered.filter(e=>year==='All years'||e.year===year);
  return <><PageHeader eyebrow={education?'05 / NEVER STOP LEARNING':'04 / THE PATH SO FAR'} title={education?'Every chapter opens a new door.':'A journey, still unfolding.'} description={education?'From early curiosity to data science research. The places and people that shaped how I think.':'Research, teaching and building — connected by curiosity. Explore the milestones, with room for what comes next.'}/>{!education&&<><div className="filter-chips year-filters" aria-label="Filter by starting year">{years.map(y=><button key={y} aria-pressed={y===year} onClick={()=>setYear(y)}>{y}</button>)}</div><p className="results-count" role="status">{entries.length} experiences · Ordered by starting date. Some chapters overlap.</p></>}<div className="road-start"><span className="status-dot"/>{education?'THE LEARNING CONTINUES':'THE JOURNEY CONTINUES'}</div><ol className={`roadmap ${education?'education-road':''}`}>{education?schools.map((s,i)=><li className="road-stop" key={s.institution}><RoadCurve/><span className="road-node"><Icon name="education"/></span><article className="road-card glass"><div className="road-card-meta"><span className="pill">{s.period}</span><span className="stop-number">0{i+1}</span></div><div className="school-heading">{s.logo&&<img src={asset(s.logo,true)} width="52" height="52" alt={`${s.institution} logo`} loading="lazy"/>}<h2>{s.institution}</h2></div><p className="school-degree">{s.degree}</p><ul className="school-details">{s.details.map(d=><li key={d}>{d}</li>)}</ul></article></li>):entries.map((e,i)=><li className="road-stop" key={e.index}><RoadCurve/><span className="road-node"><Icon name={e.icon==='faChalkboardTeacher'?'education':e.icon==='faCode'?'code':'research'}/></span><article className="road-card glass"><div className="road-card-meta"><span className="pill">{e.date}</span><span className="stop-number">{e.year}</span></div><h2>{e.title}</h2><p className="road-organization">{e.subtitle}</p>{e.location&&<p className="road-location">{e.location}</p>}<p>{e.description}</p><details><summary>Explore this chapter <Icon name="arrow"/></summary><p>{e.fullDescription}</p></details></article></li>)}</ol><div className="road-end"><GlassIcon name="spark" tone="cyan"/><p>Every step builds on the last.</p></div></>;
}
