import React, {useEffect,useState} from 'react';
import projects from '../data/ProjectsData.json';
import Icon, {GlassIcon} from '../ui/Icon';
import {PageHeader, Tags, asset, ExternalLink} from '../ui/shared';
import {Link,useRoute} from '../ui/router';
export default function Projects(){
  const {path}=useRoute();
  const [category,setCategory]=useState('Featured');
  const [query,setQuery]=useState('');
  const slug=path.split('/')[2];
  const project=projects.find(p=>p.slug===slug);
  useEffect(()=>{if(project)document.title=`${project.title} — Ali Moeinian`;},[project]);
  if(slug){
    if(!project) return <><PageHeader eyebrow="PROJECT NOT FOUND" title="An unexplored idea." description="This project link does not exist. Discover the rest of the collection."/><Link to="/projects" className="button primary">All projects <Icon name="arrow"/></Link></>;
    return <><Link to="/projects" className="back-link"><Icon name="arrow"/>All projects</Link><div className="project-detail"><div className="project-detail-copy"><p className="eyebrow">{project.category}</p><h1>{project.title}</h1><p className="lead">{project.oneLiner}</p><div className="detail-badges"><span className={`status status-${project.status.toLowerCase()}`}>{project.status}</span><span className="pill">{project.level}</span></div></div><div className="detail-image glass">{asset(project.image)?<img src={asset(project.image)} alt={`${project.title} cover`} width="800" height="500"/>:<GlassIcon name="code"/>}</div><section className="glass detail-overview"><p className="eyebrow">THE IDEA & THE WORK</p><h2>Project overview</h2><p>{project.description}</p><h3>Tools & topics</h3><Tags items={project.tags}/>{project.href&&<ExternalLink href={project.href} className="button primary">Visit project</ExternalLink>}</section><aside className="glass detail-aside"><GlassIcon name="research"/><h2>Have a related idea?</h2><p>Let’s explore what we could build or research together.</p><Link to="/contact" className="text-link">Start a conversation <Icon name="arrow"/></Link></aside></div></>;
  }
  const categories=['Featured','All projects',...Array.from(new Set(projects.map(p=>p.category)))];
  const filtered=projects.filter(p=>(category==='All projects'||(category==='Featured'?p.featured:p.category===category))&&`${p.title} ${p.description} ${p.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="03 / SELECTED WORK" title="Ideas are only the beginning." description="A collection of experiments, research and systems. From the first question to something that works."/><div className="project-toolbar"><div className="filter-chips" aria-label="Project categories">{categories.map(c=><button key={c} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search-box glass"><Icon name="search"/><span className="sr-only">Search projects in selected category</span><input type="search" placeholder="Search projects…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p className="results-count" role="status">{filtered.length} of {projects.length} projects <span> / {category}</span></p><div className="project-grid">{filtered.map(p=><article className="glass work-card" key={p.slug}><Link to={`/projects/${p.slug}`} className="work-image" aria-label={`View ${p.title}`}>{asset(p.image)?<img src={asset(p.image)} alt="" width="600" height="375" loading="lazy"/>:<GlassIcon name="code"/>}<span className={`status status-${p.status.toLowerCase()}`}>{p.status}</span><span className="work-image-arrow"><Icon name="diagonal"/></span></Link><div className="work-body"><p className="eyebrow">{p.category}</p><h2><Link to={`/projects/${p.slug}`}>{p.title}</Link></h2><p>{p.oneLiner}</p><Tags items={p.tags}/><Link to={`/projects/${p.slug}`} className="text-link">Explore project <Icon name="arrow"/></Link></div></article>)}</div>{filtered.length===0&&<div className="empty-state glass"><Icon name="search"/><h2>No matching projects.</h2><p>Try a different keyword or explore the whole collection.</p><button className="button primary" onClick={()=>{setQuery('');setCategory('All projects');}}>Reset filters</button></div>}</>;
}
